#!/usr/bin/env bash
set -euo pipefail

DNS_POLICY_DIR="/etc/paqet-dns-policy"
DNSMASQ_BLOCK_CONF="/etc/dnsmasq.d/paqet-dns-policy-blocklist.conf"
ALLOW_FILE="${DNS_POLICY_DIR}/allow_domains.txt"
META_FILE="${DNS_POLICY_DIR}/last_update"
CATEGORY_FILE="${DNS_POLICY_DIR}/category"
QUIET=0

CATEGORY="${1:-}"
if [ "${CATEGORY}" = "--quiet" ]; then
  QUIET=1
  CATEGORY="${2:-}"
elif [ "${2:-}" = "--quiet" ]; then
  QUIET=1
fi

log() {
  [ "${QUIET}" = "1" ] || echo "$@"
}

mkdir -p "${DNS_POLICY_DIR}"

if [ -z "${CATEGORY}" ] && [ -f "${CATEGORY_FILE}" ]; then
  CATEGORY="$(tr -d ' \n\r' < "${CATEGORY_FILE}")"
fi
if [ -z "${CATEGORY}" ]; then
  CATEGORY="ads"
fi
case "${CATEGORY}" in
  ads|all|proxy) ;;
  *)
    echo "Invalid category: ${CATEGORY} (allowed: ads|all|proxy)" >&2
    exit 1
    ;;
esac

TMP_RAW="$(mktemp)"
TMP_DOMAINS="$(mktemp)"
TMP_ALLOW="$(mktemp)"
TMP_OUT="$(mktemp)"
trap 'rm -f "${TMP_RAW}" "${TMP_DOMAINS}" "${TMP_ALLOW}" "${TMP_OUT}"' EXIT

fetch_from_url() {
  local url="$1"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL --connect-timeout 8 --max-time 30 "${url}" -o "${TMP_RAW}" 2>/dev/null
  elif command -v wget >/dev/null 2>&1; then
    wget -q --timeout=30 -O "${TMP_RAW}" "${url}"
  else
    echo "Neither curl nor wget is available." >&2
    return 1
  fi
}

SOURCE_URL="${DNS_POLICY_SOURCE_URL:-}"
SOURCE_USED=""
if [ -n "${SOURCE_URL}" ]; then
  if fetch_from_url "${SOURCE_URL}"; then
    SOURCE_USED="${SOURCE_URL}"
  fi
fi

if [ -z "${SOURCE_USED}" ]; then
  for url in \
    "https://raw.githubusercontent.com/bootmortis/iran-hosted-domains/release/domains/${CATEGORY}.txt" \
    "https://raw.githubusercontent.com/bootmortis/iran-hosted-domains/main/domains/${CATEGORY}.txt" \
    "https://raw.githubusercontent.com/bootmortis/iran-hosted-domains/release/${CATEGORY}.txt" \
    "https://raw.githubusercontent.com/bootmortis/iran-hosted-domains/main/${CATEGORY}.txt"
  do
    if fetch_from_url "${url}"; then
      SOURCE_USED="${url}"
      break
    fi
  done
fi

if [ -z "${SOURCE_USED}" ]; then
  echo "Failed to download DNS policy list for category '${CATEGORY}'." >&2
  exit 1
fi

awk '
  {
    gsub(/\r/, "", $0)
    sub(/#.*/, "", $0)
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", $0)
    if ($0 == "") next
    d=tolower($0)
    sub(/^domain:/, "", d)
    sub(/^full:/, "", d)
    if (d ~ /^regexp:/) next
    if (d ~ /^keyword:/) next
    sub(/^\./, "", d)
    if (d ~ /^[a-z0-9.-]+$/) print d
  }
' "${TMP_RAW}" | sort -u > "${TMP_DOMAINS}"

if [ -f "${ALLOW_FILE}" ]; then
  awk '
    {
      gsub(/\r/, "", $0)
      sub(/#.*/, "", $0)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", $0)
      if ($0 == "") next
      print tolower($0)
    }
  ' "${ALLOW_FILE}" | sort -u > "${TMP_ALLOW}"
  if [ -s "${TMP_ALLOW}" ]; then
    grep -Fvx -f "${TMP_ALLOW}" "${TMP_DOMAINS}" > "${TMP_OUT}" || true
    mv -f "${TMP_OUT}" "${TMP_DOMAINS}"
  fi
fi

{
  echo "# Generated by paqet DNS policy updater"
  echo "# category=${CATEGORY}"
  echo "# source=${SOURCE_USED}"
  while read -r domain; do
    [ -n "${domain}" ] || continue
    echo "address=/${domain}/0.0.0.0"
    echo "address=/${domain}/::"
  done < "${TMP_DOMAINS}"
} > "${TMP_OUT}"
mv -f "${TMP_OUT}" "${DNSMASQ_BLOCK_CONF}"

COUNT="$(wc -l < "${TMP_DOMAINS}" | tr -d ' ')"
{
  echo "updated_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "category=${CATEGORY}"
  echo "source=${SOURCE_USED}"
  echo "domain_count=${COUNT}"
} > "${META_FILE}"
echo "${CATEGORY}" > "${CATEGORY_FILE}"

if systemctl is-active --quiet dnsmasq 2>/dev/null; then
  systemctl reload dnsmasq >/dev/null 2>&1 || systemctl restart dnsmasq >/dev/null 2>&1 || true
fi

log "DNS policy list updated: category=${CATEGORY}, domains=${COUNT}"
log "Source: ${SOURCE_USED}"
